#Yubin Lim yl2vv
#Makefile
#April 12, 2019
#CS2150-103

CC = clang
CFLAGS = -m64 -Wall -O2 -g

OFILES = linkedlist.o

.SUFFIXES: .o .c

main: $(OFILES)
	$(CC) $(CFLAGS) $(OFILES) 

clean:
	-rm *.o a.out